name: Upload Maturin Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Publish package
      uses: PyO3/maturin-action@v1.39.0
      with:
          command: publish
          args: -p ${{ secrets.PYPIPASSWORD }} -u ${{ secrets.PYPILOGIN }}
